
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.Formatter;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JCSA
 */
public class ingresoDisco extends javax.swing.JDialog {

    /**
     * Creates new form ingresoGuia
     */
    public ingresoDisco(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocation(200,50);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaTelefono = new javax.swing.JLabel();
        cCodigo = new javax.swing.JTextField();
        etiquetaNombre = new javax.swing.JLabel();
        cAutor = new javax.swing.JTextField();
        etiquetaDireccion = new javax.swing.JLabel();
        cTitulo = new javax.swing.JTextField();
        botonIngresar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cPublicacion = new javax.swing.JTextField();
        comboGenero = new javax.swing.JComboBox<>();
        cDuracion = new javax.swing.JTextField();
        comboSello = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingreso de discos");

        etiquetaTelefono.setText("Código");

        cCodigo.setColumns(8);
        cCodigo.setText("Dar enter para generar codigo");
        cCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCodigoActionPerformed(evt);
            }
        });

        etiquetaNombre.setText("Autor");

        etiquetaDireccion.setText("Titulo");

        botonIngresar.setText("Ingresar");
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        jLabel4.setText("Año publicacion");

        jLabel5.setText("Género");

        jLabel6.setText("Duración");

        jLabel7.setText("Sello discografico");

        comboGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "balada", "clásica", "electrónica", "latinoamericana", "nacional", "pop", "reguetón", "rock", "salsa" }));

        comboSello.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EMI", "Sony", "Warner", "Universal" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaDireccion)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(etiquetaNombre)
                            .addComponent(etiquetaTelefono))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cTitulo)
                            .addComponent(cDuracion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboGenero, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cPublicacion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cAutor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cCodigo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboSello, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(botonIngresar)
                        .addGap(31, 31, 31)
                        .addComponent(botonCancelar)
                        .addGap(0, 90, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaTelefono)
                    .addComponent(cCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNombre)
                    .addComponent(cAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaDireccion)
                    .addComponent(cTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboSello, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonIngresar)
                    .addComponent(botonCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
        String m_Codigo;
        String m_Autor;
        String m_Titulo;
        int m_Publicacion;
        String m_Genero;
        double m_Duracion;
        String m_Sello;
        RegistroDisco REGISTRO;
        
        m_Codigo = cCodigo.getText();
        m_Autor = cAutor.getText();
        m_Titulo = cTitulo.getText();
        m_Publicacion = Integer.parseInt(cPublicacion.getText());
        m_Genero = (String) comboGenero.getSelectedItem();
        m_Duracion = Double.parseDouble(cDuracion.getText());
        m_Sello = (String) comboSello.getSelectedItem();
        REGISTRO = new RegistroDisco();
        
        
        if (m_Autor.equals(""))//(m_Codigo.equals("")))
        {
            JOptionPane.showMessageDialog(null,"Debe ingresar todos los datos","Error",JOptionPane.ERROR_MESSAGE);            
        }
        else
        {
            REGISTRO = new RegistroDisco(m_Codigo,m_Autor,m_Titulo,0,0,0,m_Publicacion,m_Genero,m_Duracion,m_Sello);
            try
            {
                REGISTRO.ingresar();
                JOptionPane.showMessageDialog(this,"El registro se ha grabado correctamente","Informe",JOptionPane.INFORMATION_MESSAGE);
            }
            catch (IOException excepcion)
            {
                JOptionPane.showMessageDialog(this,"Error al abrir el archivo","Error",JOptionPane.ERROR_MESSAGE);
            }
            dispose();
        }
        
    }//GEN-LAST:event_botonIngresarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void cCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCodigoActionPerformed
        RandomAccessFile archivo;
        RegistroDisco REGISTRO = new RegistroDisco("","","",0,0,0,0,"",0,"");
        String Cod = null;
        try {
            archivo = new RandomAccessFile("discos.txt", "rw");
            long tamaño, numeroRegistros;
            tamaño = archivo.length();
            System.out.println(tamaño);
            numeroRegistros = (tamaño / REGISTRO.TAMAÑO_REGISTRO);
            long Ncod = 0,N1cod = 0; 
            Ncod = (numeroRegistros + 1);
            long aux = Ncod; 
            Formatter obj = new Formatter();
            Formatter obj2 = new Formatter();
            String numeroCeros = String.valueOf(obj.format("%06d", Ncod)); //Da formato al codigo para que salga con 0 
            int indice = REGISTRO.buscar(numeroCeros);
            if(indice>=0){
                N1cod = aux + 2;
                Cod = String.valueOf(obj2.format("%06d", N1cod)); //Da formato al codigo para que salga con 0 
                cCodigo.setText(Cod);
            }else if(indice==-1){
                if(Ncod==N1cod){
                    Ncod = Ncod+3;
                }
                cCodigo.setText(numeroCeros);
            }
            cCodigo.setEditable(false);                

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error al leer el archivo");
        }  
    }//GEN-LAST:event_cCodigoActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonIngresar;
    private javax.swing.JTextField cAutor;
    private javax.swing.JTextField cCodigo;
    private javax.swing.JTextField cDuracion;
    private javax.swing.JTextField cPublicacion;
    private javax.swing.JTextField cTitulo;
    private javax.swing.JComboBox<String> comboGenero;
    private javax.swing.JComboBox<String> comboSello;
    private javax.swing.JLabel etiquetaDireccion;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaTelefono;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
