
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JCSA
 */
public class listadoDisco extends javax.swing.JDialog {

    /**
     * Creates new form listadoGuia
     */
    public listadoDisco(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocation(200,50);
        
        ArrayList Elementos;
        Elementos= new ArrayList(5);
        RegistroDisco REGISTRO;
        REGISTRO = new RegistroDisco();


         try
         {
             int j=0;
                 
             Elementos = REGISTRO.listar();

             ((DefaultTableModel)Tabla.getModel()).setNumRows(Elementos.size());

             for (int i=0; i<Elementos.size();i++)
             {
                 REGISTRO = (RegistroDisco) Elementos.get(i);
                 Tabla.setValueAt(REGISTRO.getCodigo(), j, 0);
                 Tabla.setValueAt(REGISTRO.getAutor(), j, 1);
                 Tabla.setValueAt(REGISTRO.getTitulo(), j, 2);
//                 Tabla.setValueAt(REGISTRO.getCantidad(), j, 3);
//                 Tabla.setValueAt(REGISTRO.getCosto(), j, 4);
//                 Tabla.setValueAt(REGISTRO.getPrecio(), j, 5);
                 Tabla.setValueAt(REGISTRO.getAnio(), j, 3);
                 Tabla.setValueAt(REGISTRO.getGenero(), j, 4);
                 Tabla.setValueAt(REGISTRO.getDuracion(), j, 5);
                 Tabla.setValueAt(REGISTRO.getSello(), j, 6);
                 j++;
             }
             setVisible(true);
             
         }
         catch (IOException excepcion)
         {
             JOptionPane.showMessageDialog(null, "Error al abrir el archivo");
         }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        botonRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listado discos");

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Autor", "Titulo", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        botonRegresar.setText("Regresar");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonRegresar)
                .addGap(180, 180, 180))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonRegresar)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_botonRegresarActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
